"""Add DailyMinutesListened

Revision ID: dc654b4202e8
Revises: 3a55716c02e1
Create Date: 2026-10-09 12:01:41.899921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc654b4202e8'
down_revision: Union[str, Sequence[str], None] = '3a55716c02e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_minutes_listened',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_referencia', sa.String(), nullable=False),
    sa.Column('total_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_minutes_listened_date_referencia'), 'daily_minutes_listened', ['date_referencia'], unique=False)
    op.create_index(op.f('ix_daily_minutes_listened_id'), 'daily_minutes_listened', ['id'], unique=False)
    op.create_index(op.f('ix_daily_minutes_listened_user_id'), 'daily_minutes_listened', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_minutes_listened_user_id'), table_name='daily_minutes_listened')
    op.drop_index(op.f('ix_daily_minutes_listened_id'), table_name='daily_minutes_listened')
    op.drop_index(op.f('ix_daily_minutes_listened_date_referencia'), table_name='daily_minutes_listened')
    op.drop_table('daily_minutes_listened')
    # ### end Alembic commands ###
