"""Configuração inicial do Alembic

Revision ID: f1016650d7ea
Revises: 
Create Date: 2026-10-03 10:32:35.742499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1016650d7ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks_cache', 'album_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks_cache', sa.Column('album_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
